name: Run Tests

on: [pull_request, push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.1, 8.2, 8.3]
        laravel: [9.*, 10.*, 11.*]
        stability: [prefer-stable]
        include:
          - laravel: 9.*
            testbench: 7.*
            illuminate-contracts: 9.*
            phpunit: 9.*
            pestphp: 1.*
          - laravel: 10.*
            testbench: 8.*
            illuminate-contracts: 10.*
            pestphp: 2.*
          - laravel: 11.*
            testbench: 9.*
            illuminate-contracts: 11.*
            pestphp: 2.*
        exclude:
          - laravel: 11.*
            php: 8.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require pestphp/pest:${{ matrix.pestphp }} --dev --with-all-dependencies
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "illuminate/contracts:${{ matrix.illuminate-contracts }}"  --no-interaction --no-update --dev
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: composer test
